# Generated by Django 2.2.3 on 2019-12-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnew',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productnew',
            name='image',
            field=models.ImageField(default='', upload_to='shopping/images'),
        ),
        migrations.AddField(
            model_name='productnew',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productnew',
            name='sub_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
